### ISSUE TITLE
New Campaign Initial Reports

### ISSUE THREAD

**Issue by Heilidhe** [LecksC/ASOR_Bugs#68] opened 2017-05-31 12:50 UTC
- [x] 1. FTL Doesn't have access to Long Range. (Role - ASOR Alpha FTL Blue)
- [x] 2. I spawned with a pkp and now i can't get it in the gear selector i can only take pkm
- [x] 3. No Coloured Smoke grenades
- [x] 4. VERIFY - We have access to western scopes if thats an issue
- [x] 5. VERIFY - 6B23 (6Sh116) vest is only accessible by the FTL slot
- [x] 6. No interface between JEM and Current LR Backpacks
- [x] 7. CFA Icons are correct, but are red instead of green
- [x] 8. Long range not selectable in asor gear select for FTL or SQL
- [x] 9. CFA saying they're unable to give blood and check proper vitals (no numbers, just normal blood pressure etc)
- [x] 10. ENVG-II (black) night vision goggles could be used as thermals
- [x] 11. Medical cant stitch/pak either, not even in the tent.
- [x] 12. Default short range radios are 148s which I believe are IND radios. FADAK is east. Pretty sure the default frequencies break if you're using the wrong side
- [x] 13. No Optics for PKM - VERIFIED
- [x] 14. RPG Sight Needs to Be Added
- [x] 15. Not Enough Rounds For LMG
- [x] 16. VERIFY - Engineer Backpacks too small 
- [x] 17. ammotruck1 cfgGroups
- [x] 18.  add pgo-7 rpg7 scope
- [x] 19. add ftl vest for vympel to sql also
- [x] 20. red lmg class name doesnt include squad callsign in name
- [x] 21. add faction to name so comes  up in lobby description
- [x] 22. vympel medic vest should be the olive drab color
- [x] 23. Not sure whether LMG's are meant to have the option of 3 different AK rifles?
- [x] 24. PKP = No Scope Access in GS, but does have scopes

## NEW 6/4
- [x] 25. VERIFY :Victor has access to CSAT Wetsuit as a uniform option
- [x] 26. victor missed out on faction name in slots somehow
- [x] 27. Units start with western white smokes then the GS steals them becasue they're blacklisted
- [x] 28. Bug: ak74m camo can be equipped with rpg scopes   edit: to add clarity, the rpg scopes can be selected for the ak in the gear selector.
- [x] 29. No vehicle ammo available
- [x] 30. Check heli variants, no littlebird transport type availabe
- [x] 31. backpacks for LMG/Engineer VDV

**Comment by Heilidhe** [comment] 2017-05-31 13:05
## Ranks 
- [x] VERIFY - Mission Issue
## Vehicle Selector
- [x]  Was not a Mission Issue

**Comment by suitsy** [comment] 2017-05-31 13:17
- [ ] 17. ammotruck1 cfgGroups
- [ ] 18.  add pgo-7 rpg7 scope
- [ ] 19. add ftl vest for vympel to sql also
- [ ] 20. red lmg class name doesnt include squad callsign in name
- [ ] 21. add faction to name so comes  up in lobby description
- [ ] 22. vympel medic vest should be the olive drab color

**Comment by Heilidhe** [comment] 2017-05-31 14:11
Updated Top with Suits New Issues (Just Update initial post suitsy - looks better ;) ).

**Comment by Woodsylord** [comment] 2017-06-01 00:21
3 Just add standard grenades.
4 Yes. No russian railed optics so we get these.
10 Can we just remove the stupid futuristic ones?
16 They have the engineer UMBTS. May need Carryall.
22 There isn't one from memory. Will look at other options.
23 Yes they are. 

I will go through gear list tonight to look at some fixes for the uniform issues. Might be worth having a pool of vests available for all classes.

**Comment by suitsy** [comment] 2017-06-01 01:15
7. Is that medic icon on the map? As in blueforce tracker thing.
8. Not sure why LR backpacks are not coming up, I have them included in the group whitelist - https://github.com/LecksC/ASOR/blob/master/asor_factions/factions/opfor/russia/all_groups_gear.hpp
3. I thought I added the other grenades tot he Russians also but it was only for the BKT. Seems we definitely want the standard stuff, should we just not use the Russian stuff?
See them at the bottom, unless I have made an error in the class name perhaps will need to check. - https://github.com/LecksC/ASOR/blob/master/asor_factions/factions/blufor/bekovetus/all_groups_gear.hpp
24. Seems I didnt add the PKP to the whitelist for LMG, oops. Need to see what scope fits the PKM and include that too I think. Probably worth reviewing all LMG blacklists. 
Vympel Blacklist - Line 58 shows the LMG kit -
 https://github.com/LecksC/ASOR/blob/master/asor_factions/factions/opfor/russia/spetsnaz/vympel/gear_list.hpp

**Comment by Heilidhe** [comment] 2017-06-01 05:08
Can anybody tick stuff? If you know its fixed, or know you can fix it, just tick the boxes in the intial post.. Obviously, you have to be 100% positive the issue is fixed or verified. 

@suitsy 
- Medic Icon is on Map. Reports they were just the wrong colours.

- We'll verify for Sunday.

### I will review and attempt to fix both PKP, and PKM issues as well as grenades mentioned here, this evening. 

@Woodsylord 
Also your numbering I'm a bit confused with when aligning it with the first post.. Can you just verify they're in response to the correct issue above? Bit lost sorry.

**Comment by suitsy** [comment] 2017-06-01 05:20
Yeah tick away, if it involves a change make sure its on repo so dont double up. 
I wouldnt tick stuff though that is like - This thing is broken - we know its broken dont think we need much verification - we need it fixed.

**Comment by suitsy** [comment] 2017-06-01 05:21
8. Is fixed? There is LR's in GS now?

**Comment by Heilidhe** [comment] 2017-06-01 05:23
Not sure.. I ticked it because woodsy replied to it, but as i said above, bit confused with his numbering now.

** Unticked it. Will leave it to Sunday **

**Comment by Woodsylord** [comment] 2017-06-01 06:16
8 should be 23... no clue what happened there. I'll check when home

**Comment by suitsy** [comment] 2017-06-01 06:52
23. Confirmed LMG roles still need access to standard AK's

**Comment by Woodsylord** [comment] 2017-06-01 07:20
Sorted... when I wrote it, the numbers were correct. When I previewed, it autoordered them.

**Comment by LecksC** [comment] 2017-06-01 10:16
Regarding the VS, I logged in to debug it last night and I don't think it's a mission issue. Added (hopefully) a fix for the vehicle selector with JIP/multiplayer/whatever was wrong (made 3den variables set public). https://github.com/LecksC/ASOR/commit/3b76c26a1ab74d1afa0425ef8f80bbb85e7acd9d

**Comment by Woodsylord** [comment] 2017-06-01 10:27
Added 6B23 (6Sh116)  to all units. It fits with everything.
Added AK tweaks.
Added medic vest variants
Minor helmet tweaks

https://github.com/LecksC/ASOR/commit/597f3b4996a24a7e0a7f89082fff976b20251ccd
https://github.com/LecksC/ASOR/commit/3191f1dee79f84c4b2ea951d3179a9d8c8203e89

**Comment by LecksC** [comment] 2017-06-01 11:15
Fixed number 1 and 8 (fix scope in macro)
https://github.com/LecksC/ASOR/commit/57d42ec4097c37416bb580deebbbc03b2b44f164

**Comment by LecksC** [comment] 2017-06-01 11:23
Fixed number 2 (added PKP for all Russian opfor)
https://github.com/LecksC/ASOR/commit/1ad29d7b2ac8ba6bce9349c0b38cbffcc3a45e88

**Comment by LecksC** [comment] 2017-06-01 11:57
Fixed number 6
https://github.com/LecksC/ASOR/commit/e9dad4a1328c7c863b53fcc1945d2f75ac72e03c

Fixed 12
https://github.com/LecksC/ASOR/commit/d8215c89a5cd349185a7f12cdcfa064358870a8b

Fixed 3
https://github.com/LecksC/ASOR/commit/908f79be0c6e7b15dbb36c2f9222448a0e2ad6c1

Fixed 14, 18 (RPG26s have no sights, only RPG7s).
https://github.com/LecksC/ASOR/commit/2f0a9845e586fb0a72e8a31f9c7872b43b56f27e

Fixed 15
https://github.com/LecksC/ASOR/commit/18d2b2d8bb546460674cad0984445304e1e749a5

Fixed 10
https://github.com/LecksC/ASOR/commit/882f382ac89cfeac1b61d77f99d324e8cef63cc9

Fixed 24 - PKM has no scope, only PKP
https://github.com/LecksC/ASOR/commit/0f2d0044248a50de0d10ccdf073567a7bd4e44bc

**Comment by Heilidhe** [comment] 2017-06-01 14:28
I actually had the VS sign and pads synced properly last night - I replaced the pads again and synced and it worked.. so was believing it was a Mission issue.. not sure how though. Either way, it does work.. and was working after last nights op for me..

**Comment by suitsy** [comment] 2017-06-01 22:59
6. and 12. Any reason why we adding the other backpacks? Really dont want to use the shitty TFAR models, just want to use the better backpacks we currently use with all factions. There is a flat green version for this (not amcu) We will need to use the 152 for personnel radios to remain compatible also.

_ 14. May as well only give the RPG7 sites to AT classes since they are only ones that have access to them instead of everyone in the GROUP. (be good for rebels not to have them anyway so needs to be in the actual faction list either way)

_ 15. Does that actually work @LecksC just adding more, I think the comments were they could only fit 4 lmg mags in the bag not that they were just not there?

**Comment by suitsy** [comment] 2017-06-02 00:12
. 5. Verified and updated so SQL has access to same vest
. 17. Fix on repo - https://github.com/LecksC/ASOR/commit/162b098e607752bae64a80f5c73b9aafa85ae525
. 19. Fix, added ftl vest to sql
. 20. Was FTL not LMG added squad to unit description - https://github.com/LecksC/ASOR/commit/dce9791af4edc3b8f9046a8559c201d0ba4bed63

**Comment by LecksC** [comment] 2017-06-02 02:28
re 6 and 12, we sorta need to use opfor radios unless we wanna patch every opfor vehicle's radios. If you want the different models, can make a duplicate of the 'west' backpack for 'east' that inherits from the mr3000 or bussole instead. I think we're only going to have issues if we try and use blufor radios as opfor.. will be too hard to replace them everywhere.

re 15, yeah, spawning in as an MG you now have 8 boxes (1 in gun, 7 in backpack). Backpack is full with those 8.

re 14 and 18, moved RPG stuff to spetnatz/army as requested https://github.com/LecksC/ASOR/commit/ab93387ec02e49f667f8d23a9bb2896aa6046196

**Comment by suitsy** [comment] 2017-06-02 03:33
re 15. updated backpack to accommodate extra rounds for vympel LMG and Engineer - https://github.com/LecksC/ASOR/commit/cfece7bd4be5fac9e7fd122ae58c7e9d022b8b2e

**Comment by LecksC** [comment] 2017-06-02 04:37
does someone keep unticking some of these(including number 1)? these ticks seem buggy.

Did 21 https://github.com/LecksC/ASOR/commit/37fe870628e5ec78f7cac2e1402decb3e83dcdec

**Comment by LecksC** [comment] 2017-06-02 04:45
I think that's everything ready for another round of testing at least?

Still not sure about number 7.

Have set attendent to 2 to see if that works for the medics (9 and 11) https://github.com/LecksC/ASOR/commit/3d5ff70f7026c2c6e882ca674e478ff4a0b2af91

**Comment by Woodsylord** [comment] 2017-06-02 10:32
MI-28 doesn't seem to have any ammo.

Could be due to update breaking ammo types.

**Comment by suitsy** [comment] 2017-06-04 22:25
re 9 and 11 - fixed, was tracker overriding medical setting. - https://github.com/LecksC/ASOR/commit/b5f6013bb7b779ad2c358f587a1912061507a835

re 7. Fixed medic icon color, had it set to blue or red, not green in config.

25. Wetsuits were in, removed them all from each faction not needed much if ever. can put them in easily when needed.

re 27. There is no blacklist anymore so not sure why GS will not allow them. Any ideas on that one @LecksC ?

re 29. added veh ammo/fuel to all factions (probably not required for all factions, might look at making a single box later and allowing for all factions)

31. added larger backpacks for LMG/ENG

**Comment by Woodsylord** [comment] 2017-06-04 23:11
For 28, I had a look at this. These are the three AK optics that I put in. Not RPG optics.

**Comment by suitsy** [comment] 2017-06-04 23:13
Was the AK with Russian optics requested?? Did look cool ppl carrying actual wood variant ak's, would only allow them for vdv though, leave sf with newer variants.

**Comment by Woodsylord** [comment] 2017-06-04 23:48
SF have the NPZ and Zentico ones. Western optics only. Will double check but 90% sure.

But yes, some people requested.

**Comment by LecksC** [comment] 2017-06-05 04:54
re 27, I didn't add white smoke (only coloured smoke) to the whitelist because there's a Russian white one.

**Comment by suitsy** [comment] 2017-06-05 05:42
@LecksC yeah ok that makes sense, checked and the default smoke was the nato one, changed it to Russian so 27. done. - https://github.com/LecksC/ASOR/commit/99e1cf47d8615d5b266e8fbec4c95220179bcde9

re 26. updated the missing displaynames - https://github.com/LecksC/ASOR/commit/1b7cec7d1386bd117dc9868c25734f535208154d

**Comment by suitsy** [comment] 2017-06-05 06:00
re 30. Going to move the vehicle selector whitelist from common into each faction just like the gear list so we can add manual vehicles that are not part of the config for the faction. 

Seems there is a sfp_bo105_unarmed heli, I have used Sfp_bo105 in the config, fixed. Also removed the MI28 to dodge the no ammo issue. 

I reckon we close this ticket and start a new one for any future changes, getting kinda long.

**Comment by suitsy** [comment] 2017-06-05 06:00
All items completed.

**Closed as completed by suitsy** 2017-06-05 06:00 UTC
Labels: Bug, Urgency - Now, Needs Verification, Needs Testing
