### ISSUE TITLE
Non Combatant Module Updates

### ISSUE THREAD

**Issue by LecksC** [LecksC/ASOR_Bugs#22] opened 2017-03-22 15:24 UTC
<a href="https://github.com/suitsy"><img src="https://avatars3.githubusercontent.com/u/13358761?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [suitsy](https://github.com/suitsy)**
_Tuesday Mar 07, 2017 at 00:01 GMT_
_Originally opened as https://github.com/LecksC/ASOR/issues/17_

----

1. 	Add uniforms and vest as factor for discovery
2. 	Add option to module to set enemy side
3. 	Add ability to link units to module as non combatants instead of all players

**Comment by suitsy** [comment] 2017-03-24 00:46
4. Fix how this operates, currently set to server, needs to run local on clients.

**Comment by Instant-Muffin** [comment] 2017-05-16 13:08
Uniform check has been added and the script is now spawned on each client instead of looping over each player and running on the server. JIP possibly also fixed, needs to be tested on the server.

**Comment by suitsy** [comment] 2017-05-17 22:24
Any chance we could test this with a few people on the weekend? I should be around.

**Comment by Instant-Muffin** [comment] 2017-05-18 05:02
Basic server test has it working, will do a larger test this Saturday.

**Comment by Instant-Muffin** [comment] 2017-05-29 08:18
Module working as intended in mission. Things to do:
1. Restricted Areas.
2. AI that threaten and yell at players when they do things they shouldn't.
3. Incognito indicator (possibly a small, mostly transparent icon above the radar that indicates if you're hidden or not?)

**Comment by suitsy** [comment] 2017-06-06 11:58
4. Detect NV_Goggles for night ops.
5. Add eventhandler on killed set captive
6. Add throw detection

**Comment by suitsy** [comment] 2017-06-06 12:23
5. Add eventhandler on killed set captive

**Comment by Woodsylord** [comment] 2017-06-06 12:53
Ski masks? Our guys love them... police don't. Perhaps have those with bad uniforms?

**Comment by suitsy** [comment] 2017-06-06 13:08
1. Restricted 'areas' working, currently got it just hinting player "Guards are suspicious of your activity" until we can get something else in. 

Works by using a AE Position module, radius determines restricted area, have a field to set the warning distance, so can be different distance for each position if you wanted - default 20.
Link it to the NC module and its gtg. Turns player to a combatant if they go in it.

**Comment by Instant-Muffin** [comment] 2017-06-09 08:31
UI icon has been added above Shacktac that indicates when the player is captive. Not sure about whether this should be shown always when captive or only when not holding a weapon, not wearing a vest and have been seen. Might take the tension out a little.
The module also now only runs on players that have been synced to it rather than on every player in the game.

**Comment by suitsy** [comment] 2019-04-08 00:49
renamed asor_incogneto - moving to new ticket

**Closed as completed by suitsy** 2019-04-08 00:49 UTC
Labels: Bug, asoredit, Urgency - Soon, Needs Testing
